# Configurazione del server
server:
  port: 8083
  error:
    include-message: always
    include-stacktrace: always
  servlet:
    context-path: /

# Configurazione di SpringDoc/OpenAPI
springdoc:
  api-docs:
    enabled: true
    path: /orchestrator-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /orchestrator-service/swagger-ui.html
    layout: BaseLayout
    operationsSorter: method

# Logging
logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
    com.gabriele: INFO

# Configurazione del datasource MySQL
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/order_management_system
    username: root
    password: admin

  cloud:
    stream:
      function:
        definition: processor
      bindings:
        processor-in-0:
          destination: create-order
        processor-out-0:
          destination: update-order
      kafka:
        binder:
#          replication-factor: 1
          brokers: kafka:9092

service:
  endpoints:
    inventory: http://inventory-service:8086
    payment: http://payment-service:8082