version: '3.8'
networks:
  network-kafka:
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    networks:
      - network-kafka
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    hostname: kafka
    networks:
      - network-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-user-interface:
    image: provectuslabs/kafka-ui
    container_name: kafka-user-interface
    ports:
      - "8085:8080"
    networks:
      - network-kafka
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

#  orchestrator:
#    build: ./orchestrator_service/
#    image: orchestrator
#    ports:
#      - 8083:8083
#    hostname: orchestrator
#    container_name: orchestrator
#    networks:
#      - network-kafka
#    environment:
#      - SERVER_SERVLET_CONTEXT_PATH=/orchestrator-service
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  order-service:
    build: ./order_service/
    image: order-service
    ports:
      - 8080:8080
    hostname: order
    container_name: order-service
    networks:
      - network-kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SERVICE_ENDPOINTS_INVENTORY=http://inventory-service:8086/inventory-service

#  payment-service:
#    build: ./payment_service/
#    image: payment-service
#    ports:
#      - 8082:8082
#    hostname: payment
#    container_name: payment-service
#    networks:
#      - network-kafka
#    environment:
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  inventory-service:
    build: ./inventory_service/
    image: inventory-service
    ports:
      - 8086:8086
    hostname: inventory
    container_name: inventory-service
    networks:
      - network-kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092