# Configurazione del datasource MySQL
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/order_management_system
    username: root
    password: admin

  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      function:
        definition: supplier;consumer
      bindings:
        supplier-out-0:
          destination: create-order
        consumer-in-0:
          destination: update-order

# Configurazione del server
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
  servlet:
    context-path: /

# Configurazione di SpringDoc/OpenAPI
springdoc:
  api-docs:
    enabled: true
    path: /order-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /order-service/swagger-ui.html
    layout: BaseLayout
    operationsSorter: method

# Logging
logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
    com.gabriele: INFO

# Configurazione dei servizi esterni
service:
  endpoints:
    inventory: http://inventory-service:8086