# Configurazione del datasource MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/order_management_system
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
  cloud:
    stream:
          kafka:
            binder:
              brokers: kafka:9092
          function:
            definition: supplier;consumer
          bindings:
            supplier-out-0:
              destination: create-order
            consumer-in-0:
              destination: update-order

# Configurazione del server
server:
  port: 8087
  error:
    include-message: always
    include-stacktrace: always
  servlet:
    context-path: /order-service

# Configurazione di SpringDoc/OpenAPI
springdoc:
  swagger-ui:
    enabled: true
    layout: BaseLayout
    operationsSorter: method
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# Logging
logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
    com.gabriele: INFO

# Configurazione dei servizi esterni
service:
  endpoints:
    inventory: http://inventory:8086/inventory-service

# Configurazione Spring Cloud Stream per Kafka