# Configurazione del datasource MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/order_management_system
    username: root
    password: admin
  jpa:
    show-sql: true
    # properties:
    #   hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

# Configurazione del server
server:
  port: 8086
  servlet:
    context-path: /

# Configurazione di SpringDoc/OpenAPI
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    # Configurazione di Swagger UI Layout (opzionale)
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    layout: BaseLayout
    operationsSorter: method

# Logging
logging:
  level:
    root: ERROR
    org:
      springframework: ERROR
    com.gabriele: DEBUG # Modifica questo in base al tuo package principale

# (Opzionale) Configurazione Hibernate per JPA
hibernate:
  ddl-auto: update # Aggiorna automaticamente lo schema
  use-new-id-generator-mappings: true